@echo off
echo game.bin
sr w:\game.bin GAME.SDF
echo gmcga.bin
sr w:\gmcga.bin GMCGA.SDF
echo gmega.bin
sr w:\gmega.bin GMEGA.SDF
echo gmhgc.bin
sr w:\gmhgc.bin GMHGC.SDF
echo gmmcga.bin
sr w:\gmmcga.bin GMMCGA.SDF
echo gmtga.bin
sr w:\gmtga.bin GMTGA.SDF
echo stdply.bin
sr w:\stdply.bin STDPLY.SDF
echo stick.bin
sr w:\stick.bin STICK.SDF
echo zeliad.exe
sr w:\zeliad.exe ZELIAD.SDF
echo zr1_00.bin
sr w:\zr1_00.bin ZR1_00.SDF
echo zr1_01.bin
sr w:\zr1_01.bin ZR1_01.SDF
echo zr1_02.bin
sr w:\zr1_02.bin ZR1_02.SDF
echo zr1_03.bin
sr w:\zr1_03.bin ZR1_03.SDF
echo zr1_04.bin
sr w:\zr1_04.bin ZR1_04.SDF
echo zr1_05.bin
sr w:\zr1_05.bin ZR1_05.SDF
echo zr1_06.bin
sr w:\zr1_06.bin ZR1_06.SDF
echo zr1_07.bin
sr w:\zr1_07.bin ZR1_07.SDF
echo zr1_08.bin
sr w:\zr1_08.bin ZR1_08.SDF
echo zr1_09.bin
sr w:\zr1_09.bin ZR1_09.SDF
echo zr1_10.bin
sr w:\zr1_10.bin ZR1_10.SDF
echo zr1_11.bin
sr w:\zr1_11.bin ZR1_11.SDF
echo zr1_24.bin
sr w:\zr1_24.bin ZR1_24.SDF
echo zr1_30.bin
sr w:\zr1_30.bin ZR1_30.SDF
echo zr2_00.bin
sr w:\zr2_00.bin ZR2_00.SDF
echo zr2_01.bin
sr w:\zr2_01.bin ZR2_01.SDF
echo zr2_02.bin
sr w:\zr2_02.bin ZR2_02.SDF
echo zr2_03.bin
sr w:\zr2_03.bin ZR2_03.SDF
echo zr2_04.bin
sr w:\zr2_04.bin ZR2_04.SDF
echo zr2_05.bin
sr w:\zr2_05.bin ZR2_05.SDF
echo zr2_06.bin
sr w:\zr2_06.bin ZR2_06.SDF
echo zr2_07.bin
sr w:\zr2_07.bin ZR2_07.SDF
echo zr2_08.bin
sr w:\zr2_08.bin ZR2_08.SDF
echo zr2_09.bin
sr w:\zr2_09.bin ZR2_09.SDF
echo zr2_10.bin
sr w:\zr2_10.bin ZR2_10.SDF
echo zr2_12.bin
sr w:\zr2_12.bin ZR2_12.SDF
echo zr2_13.bin
sr w:\zr2_13.bin ZR2_13.SDF
echo zr2_14.bin
sr w:\zr2_14.bin ZR2_14.SDF
echo zr2_15.bin
sr w:\zr2_15.bin ZR2_15.SDF
echo zr2_16.bin
sr w:\zr2_16.bin ZR2_16.SDF
echo zr2_17.bin
sr w:\zr2_17.bin ZR2_17.SDF
echo zr2_36.bin
sr w:\zr2_36.bin ZR2_36.SDF
echo zr2_38.bin
sr w:\zr2_38.bin ZR2_38.SDF
echo zr2_39.bin
sr w:\zr2_39.bin ZR2_39.SDF
echo zr3_00.bin
sr w:\zr3_00.bin ZR3_00.SDF
echo zr3_14.bin
sr w:\zr3_14.bin ZR3_14.SDF
echo zr3_16.bin
sr w:\zr3_16.bin ZR3_16.SDF
echo zr3_20.bin
sr w:\zr3_20.bin ZR3_20.SDF
echo zr3_22.bin
sr w:\zr3_22.bin ZR3_22.SDF
echo zr3_26.bin
sr w:\zr3_26.bin ZR3_26.SDF
echo zr3_31.bin
sr w:\zr3_31.bin ZR3_31.SDF
echo zr3_32.bin
sr w:\zr3_32.bin ZR3_32.SDF
echo zr3_33.bin
sr w:\zr3_33.bin ZR3_33.SDF
echo zr3_34.bin
sr w:\zr3_34.bin ZR3_34.SDF
echo zr3_35.bin
sr w:\zr3_35.bin ZR3_35.SDF
echo zr3_37.bin
sr w:\zr3_37.bin ZR3_37.SDF
echo Done.
exit
