[sdl]
output=surface
windowresolution=original

[dosbox]
machine=vga
# Dumps written to dosbox-x working directory (c:/dosbox-x/)

[cpu]
cycles=auto
cputype=auto

[debugger]
# debugger: starts in the debugger console so we can set breakpoints before running
debuggerrun=debugger

[autoexec]
mount c "c:\Projects\Zeliard\1_OriginalGame"
mount d "c:\dosbox-x"
c:
zeliad
