/* Active VGA palette.
 *
 * The palette is loaded as a flat 256-entry RGB table from
 * palettes_extracted.h (auto-generated by scripts/extract_palettes.py
 * from 3_Assembly/dumps/palette_rows.json — the DOSBox-X debug-overlay
 * capture of the in-game DAC state at each scene transition).
 *
 * The original game generates its palette at runtime via
 * write_palette_byte_mcga (105GDMCA.asm:2201), driven by a small bias
 * table.  Porting that synthesis routine is on the follow-up list; for
 * now we just embed the captured 256-entry outputs since they are the
 * authoritative ground truth (validated visually against the original
 * title rendering — red logo at 0xAA, teal outline at 0xCC).
 */

#include "palette.h"
#include "palettes_extracted.h"
#include "../platform/platform.h"
#include <string.h>

palette_color_t g_palette[256];

void palette_set_scene(palette_scene_t scene) {
    const palette_color_t *src;
    const char *name;
    switch (scene) {
        case PALETTE_OPENING:  src = P1_OPENING;  name = "P1_Opening";  break;
        case PALETTE_TITLE:    src = P2_TITLE;    name = "P2_Title";    break;
        case PALETTE_GAMEPLAY: src = P3_GAMEPLAY; name = "P3_Gameplay"; break;
        default:
            platform_log("palette_set_scene: unknown scene %d", scene);
            memset(g_palette, 0, sizeof(g_palette));
            return;
    }
    memcpy(g_palette, src, sizeof(g_palette));
    platform_log("palette_set_scene: %s loaded (256 entries)", name);
}
