#!/usr/bin/env python3
"""
Extract the three captured VGA palettes from
3_Assembly/dumps/palette_rows.json into a C header consumed by the engine.

Source provenance (per CLAUDE.md "Captured Palettes"):
  DOSBox-X video debug overlay shows 4 swatch rows of 64 entries each
  (RPAL6 + EPAL6 + ACPAL + CSPAL) = 256-entry VGA DAC palette.  The
  palette_rows.json file captures those swatches per scene (P1=Opening,
  P2=Title, P3=Gameplay) and is the authoritative source — the .act
  files and palettes.json in the same dumps dir were sampled from the
  wrong region of the debug overlay and contain wrong colours.

Visual validation: 2_SAR/Tools/grp_viewer rendering of the title logo
shows a red logo (palette index 0xAA) with teal outline (0xCC) which
matches P2_Title's (0xAA = (248,0,0)) / (0xCC = (0,124,124)).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

REPO    = Path(__file__).resolve().parents[2]
SRC     = REPO / '3_Assembly' / 'dumps' / 'palette_rows.json'
DEST    = REPO / '6_WebPort' / 'engine' / 'render' / 'palettes_extracted.h'

PALETTE_KEYS = [
    ('P1_Opening',  'P1_OPENING'),
    ('P2_Title',    'P2_TITLE'),
    ('P3_Gameplay', 'P3_GAMEPLAY'),
]


def emit_palette(name: str, entries: list[tuple[int, int, int]]) -> list[str]:
    out: list[str] = []
    out.append(f'static const palette_color_t {name}[256] = {{')
    for i in range(0, 256, 4):
        cells = []
        for j in range(4):
            if i + j < 256:
                r, g, b = entries[i + j]
                cells.append(f'{{{r:3d},{g:3d},{b:3d}}}')
        out.append('    ' + ', '.join(cells) + ',')
    out.append('};')
    return out


def main() -> int:
    if not SRC.exists():
        print(f'missing {SRC}')
        return 1
    raw = json.loads(SRC.read_text())

    lines: list[str] = []
    lines.append('/* AUTO-GENERATED by 6_WebPort/scripts/extract_palettes.py — DO NOT EDIT.')
    lines.append(' *')
    lines.append(' * Source: 3_Assembly/dumps/palette_rows.json (DOSBox-X debug-overlay capture).')
    lines.append(' * Each palette = 256 entries × RGB.  Used by render/palette.c.')
    lines.append(' *')
    lines.append(' * Re-run extract_palettes.py if the source JSON is updated.')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef ZELIARD_PALETTES_EXTRACTED_H')
    lines.append('#define ZELIARD_PALETTES_EXTRACTED_H')
    lines.append('')
    lines.append('#include "palette.h"')
    lines.append('')

    for json_key, c_name in PALETTE_KEYS:
        if json_key not in raw:
            print(f'WARN: {json_key} missing from JSON')
            continue
        rows = raw[json_key]
        flat = [tuple(c) for row in rows for c in row]
        if len(flat) != 256:
            print(f'WARN: {json_key} has {len(flat)} entries (expected 256)')
            continue
        lines.append(f'/* {json_key}: 256 entries.  Sample: '
                     f'[0x00]={flat[0]} [0x88]={flat[0x88]} [0xAA]={flat[0xAA]} [0xCC]={flat[0xCC]} */')
        lines.extend(emit_palette(c_name, flat))
        lines.append('')

    lines.append('#endif')
    lines.append('')
    DEST.write_text('\n'.join(lines), encoding='utf-8')
    print(f'wrote {DEST.relative_to(REPO)}  ({sum(1 for _ in lines)} lines)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
