#!/usr/bin/env python3
"""run.py — discover and run every functest under
placeholder_id/, proc_equivalence/, regression/.

Each test is a Python script with a final line of the form
    VERDICT: PASS|FAIL|REFUTED|INCONCLUSIVE: <message>
We capture each script's stdout, scrape the verdict, and aggregate
into STATUS.md.

Usage
-----
  python run.py                  # run all
  python run.py --filter '*gold*' # glob filter on test path
  python run.py --ci             # CI mode: terse table, exit 1 on FAIL
"""
import argparse
import os
import re
import subprocess
import sys
import time
from fnmatch import fnmatch
from pathlib import Path

HERE = Path(__file__).resolve().parent
CATEGORIES = ('placeholder_id', 'proc_equivalence', 'regression')

VERDICT_RE = re.compile(
    r'^VERDICT:\s+(PASS|FAIL|REFUTED|INCONCLUSIVE)\s*:?\s*(.*)$',
    re.MULTILINE | re.IGNORECASE,
)


def discover() -> list[Path]:
    out: list[Path] = []
    for cat in CATEGORIES:
        d = HERE / cat
        if not d.exists():
            continue
        out.extend(sorted(d.glob('test_*.py')))
    return out


def scrape_verdict(stdout: str) -> tuple[str, str]:
    """Return (verdict, message).  If no VERDICT line, fall back to a
    legacy heuristic: tests written before the convention printed
    'PASS' / 'FAIL' tokens at the bottom — accept those too."""
    matches = VERDICT_RE.findall(stdout)
    if matches:
        verdict, msg = matches[-1]   # last line wins
        return verdict.upper(), msg.strip()
    # Legacy fallback
    tail = stdout.strip().splitlines()[-20:]
    joined = '\n'.join(tail).upper()
    if 'PASS' in joined and 'FAIL' not in joined:
        return 'LEGACY-PASS', '(no VERDICT line; inferred from output)'
    if 'FAIL' in joined:
        return 'LEGACY-FAIL', '(no VERDICT line; inferred from output)'
    return 'NO-VERDICT', '(test produced no PASS/FAIL/VERDICT signal)'


def run_one(test_path: Path) -> dict:
    rel = test_path.relative_to(HERE)
    t0 = time.monotonic()
    env = {**os.environ, 'PYTHONIOENCODING': 'utf-8'}
    proc = subprocess.run(
        [sys.executable, str(test_path)],
        capture_output=True, text=True, encoding='utf8', errors='replace',
        env=env,
    )
    elapsed = time.monotonic() - t0
    if proc.returncode != 0:
        verdict, msg = 'CRASH', f'exit {proc.returncode}'
    else:
        verdict, msg = scrape_verdict(proc.stdout)
    return {
        'path':     rel,
        'category': rel.parts[0],
        'verdict':  verdict,
        'message':  msg,
        'elapsed':  elapsed,
        'stdout':   proc.stdout,
        'stderr':   proc.stderr,
        'rc':       proc.returncode,
    }


def write_status(results: list[dict]) -> Path:
    out = HERE / 'STATUS.md'
    lines = [
        '# functest status',
        '',
        '_Auto-generated by `run.py`; do not edit by hand._',
        '',
        '| Category | Test | Verdict | Message | Time |',
        '|---|---|:---:|---|---:|',
    ]
    for r in results:
        msg = (r['message'] or '').replace('|', '\\|').replace('\n', ' ')
        if len(msg) > 80:
            msg = msg[:77] + '...'
        lines.append(
            f'| {r["category"]} | [{r["path"].name}]({r["path"].as_posix()}) '
            f'| {r["verdict"]} | {msg} | {r["elapsed"]:.1f}s |'
        )
    lines.append('')
    out.write_text('\n'.join(lines), encoding='utf8')
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--filter', help='glob filter on test path (e.g. "*gold*")')
    ap.add_argument('--ci', action='store_true',
                    help='terse one-line-per-test output; nonzero exit on FAIL/CRASH')
    ap.add_argument('--verbose', '-v', action='store_true',
                    help='print stdout for each test')
    args = ap.parse_args()

    tests = discover()
    if args.filter:
        tests = [t for t in tests if fnmatch(str(t.relative_to(HERE)), args.filter)]
    if not tests:
        print('no tests matched')
        return 1

    print(f'Running {len(tests)} test(s)...')
    results: list[dict] = []
    for t in tests:
        r = run_one(t)
        results.append(r)
        if args.ci:
            print(f'  [{r["verdict"]:<14}] {r["path"]}  ({r["elapsed"]:.1f}s)')
        else:
            print(f'  {r["path"]}: {r["verdict"]} — {r["message"]} ({r["elapsed"]:.1f}s)')
        if args.verbose:
            print('    stdout:')
            for line in r['stdout'].splitlines():
                print(f'      {line}')
            if r['stderr']:
                print('    stderr:')
                for line in r['stderr'].splitlines():
                    print(f'      {line}')

    status_path = write_status(results)
    print(f'\nStatus table written to {status_path.relative_to(HERE.parent)}')

    # Exit code
    bad = {'FAIL', 'CRASH', 'LEGACY-FAIL'}
    n_bad = sum(1 for r in results if r['verdict'] in bad)
    n_pass = sum(1 for r in results if r['verdict'] in ('PASS', 'LEGACY-PASS'))
    n_other = len(results) - n_bad - n_pass
    print(f'  PASS: {n_pass}   FAIL/CRASH: {n_bad}   other: {n_other}')
    return 1 if n_bad else 0


if __name__ == '__main__':
    sys.exit(main())
